[package]
name = "swamp-build"
version = "0.1.0"
authors = ["Damien Broka <damienbroka@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
proc-macro2 = "*"
Inflector = "*"
syn = { version = "*", features = [ "full" ] }
quote = "*"
tonic-build = "*"
